"""initial

Revision ID: fed2deb0dfe6
Revises: 36a8069d5f9b
Create Date: 2026-05-22 00:49:36.976871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fed2deb0dfe6'
down_revision: Union[str, Sequence[str], None] = '36a8069d5f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.alter_column('disclosure_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.alter_column('disclosure_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
